### ISSUE TITLE
.gitignore removes Models from repository

### ISSUE THREAD

**Issue by KillerGoldFisch** [FaberSan/Zeckoxe#1]
The `.gitignore` contains an entry for `*.obj` files. This prevents the Wavefront OBJ modedels from adding to this repository.

https://github.com/FaberSan/Direct3D11-Tutorials/blob/eb1ce6475f3b03c00c7a426531debb70d4357e77/.gitignore#L66

Without any C++ projects, it would make sense to simply remove the line.

Cheers.

**Comment by FaberSan** [comment]
Hello @KillerGoldFisch,

The examples that pass to another repository due to **SharpDX** are no longer maintained, those that create from scratch with [Vortice.Windows](https://github.com/amerkoleci/Vortice.Windows),
Sorry for my English.

Regards
